### ISSUE TITLE
Support for "radio"

### ISSUE THREAD

**Issue by SevereOverfl0w** [SubmarinerApp/Submariner#108]
Airsonic & the DSub client both have support for "Radio", which seems to fetch a mix of songs from similar artists of a selected one.

**Comment by NattyNarwhal** [comment]
Should be the [`getSimilarSongs`(2)](http://www.subsonic.org/pages/api.jsp#getSimilarSongs) endpoint. I suspect the way this would work in UX at least for an MVP would be appending to the tracklist.

**Comment by NattyNarwhal** [comment]
Another solution that can be applied more generally is a view that can be used for generic "show me something results" like the playlist view, but probably not the playlist view (as I believe that assumes a playlist object).
