### ISSUE TITLE
When using Navidrome, clicking star rating returns unsupported URL

### ISSUE THREAD

**Issue by jboxman** [SubmarinerApp/Submariner#120]
I'm able to connect successfully and the entire library loads. When trying to rate a track, however, a window pops up that says "unsupported URL". The rating doesn't seem to show up in the Navidrome UI, so I don't think it gets saved. It seems to persist locally, however.

**Comment by NattyNarwhal** [comment]
Navidrome, at least the version I have installed, doesn't support ratings; only starring (which isn't supported yet, see GH-113). As you noted though, it should persist locally in the database even it it can't send it out to the server.

**Comment by NattyNarwhal** [comment]
Ideally, we should hide things if the other end doesn't support them, but this is a bit hard considering the Subsonic API has no real way to declare a supported featureset. All we can really rely on is the API endpoint returning unsupported feature when actually used.

**Comment by NattyNarwhal** [comment]
closing because navidrome does have star ratings, and opensubsonic promises to make it possible to determine supported features ahead of time. we're not using it yet, but we probably will in the future
