### ISSUE TITLE
Unable to login to play.asti.ga (Astiga)

### ISSUE THREAD

**Issue by Mateus109** [SubmarinerApp/Submariner#136]
> Subsonic Error (code 40)
> Wrong username or password

When using Submariner with Astiga

**Comment by NattyNarwhal** [comment]
Have you tried with or without token auth?

**Comment by Mateus109** [comment]
> Have you tried with or without token auth?

Yeah, tried both.  I guess Subsonic simply doesn't work with Astiga.

**Comment by NattyNarwhal** [comment]
I haven’t heard of Astiga before, but I’ll check it. 

In the meantime, what version are you using? Are you using the MAS version or the one from the website? Do you have any entries for your server in Keychain?

**Comment by Mateus109** [comment]
The web version.  It works with other Subsonic apps I tested (e.g. Substreamer).

**Comment by NattyNarwhal** [comment]
I just signed up for Astiga and I can't seem to reproduce this. I'm thinking it might be a keychain issue (i.e. similar to GH-125).

Is it in Keychain Access, like so?

![Screenshot 2023-06-13 at 10 17 53 PM](https://github.com/SubmarinerApp/Submariner/assets/3161292/e2579a41-9812-4871-85bc-8927f7bdae22)

**Comment by Mateus109** [comment]
<img width="1136" alt="image" src="https://github.com/SubmarinerApp/Submariner/assets/11629946/f0e86111-6570-4df6-8ffe-d653c249324a">
<img width="372" alt="image" src="https://github.com/SubmarinerApp/Submariner/assets/11629946/ee2be663-561e-4aea-a1af-22efa1c1f1cb">
<img width="646" alt="image" src="https://github.com/SubmarinerApp/Submariner/assets/11629946/d65d7c53-7cbc-4aa1-a886-9ebc3ddb74a8">

**Comment by Mateus109** [comment]
Are there any local application logs I can view?

**Comment by NattyNarwhal** [comment]
Logs are in Console.app when setting.

**Comment by Mateus109** [comment]
OK, so there's a lot of info in Console when running Submariner.  But the following faults seem to occur when setting up Submariner:

`Error connecting to remote endpoint: (null)'
fault: Unable to create token NSXPCConnection.  NSXPCStoreServerEndpointFactory 0x13ce67870 -newEndpoint returned nil'
CoreData: Unable to create token NSXPCConnection.  NSXPCStoreServerEndpointFactory 0x13ce67870 -newEndpoint returned nil`

**Comment by NattyNarwhal** [comment]
Unfortunately you do get a lot of noise in the console. I'm cleaning up some code, but I'll look at this and try to do a build.

**Comment by NattyNarwhal** [comment]
[Submariner-2.2-20230615TestBuild.zip](https://github.com/SubmarinerApp/Submariner/files/11753306/Submariner-2.2-20230615TestBuild.zip)

Try this build; it's based on the latest commit, and I've made some improvements to Keychain support (if that's the problem) since last release. Relevant messages for Keychain-related problems in the console will mention `SBServer.password`; ones adjacent may be related.

**Comment by Mateus109** [comment]
That seems to have fixed the problem! :)

**Comment by NattyNarwhal** [comment]
Looks like I'll have to push a release soon then...
