### ISSUE TITLE
Navidrome Scrobbling not working

### ISSUE THREAD

**Issue by pierrec18** [SubmarinerApp/Submariner#140]
Hello,

When I listen to my music on Submariner, scrobbling with Last.fm in my Navidrome app is not working. It seems to be the same issue as described here: https://github.com/navidrome/navidrome/issues/2347

Is it possible to implement a solution for this in your app?

Thank you.

Pierre

**Comment by NattyNarwhal** [comment]
Seems like the easiest solution is to just always scrobble, even if we're playing the remote stream URL. I thought we only needed to do when playing a local resource representing a remote resource.
