### ISSUE TITLE
How do I switch to dark mode? 

### ISSUE THREAD

**Issue by twedu** [SubmarinerApp/Submariner#145]
How do I switch to dark mode? The image on the official website is dark, so I'd like to know how to switch. Is there a way to sync data between Navidrome and Submariner, so that I can delete cached music on Submariner?

**Comment by NattyNarwhal** [comment]
Go to system preferences/settings and switch it to dark mode. On macOS 13:

![Screenshot 2023-07-14 at 11 13 21 AM](https://github.com/SubmarinerApp/Submariner/assets/3161292/662fb3b4-d365-4aae-9865-b2c22b2e63f2)

**Comment by NattyNarwhal** [comment]
Also WRT syncing library state, this has been mostly fixed in code committed past 2.3.1 so that it deletes items removed from the remote library if you try to access them.
