### ISSUE TITLE
When I connect Navidrome server

### ISSUE THREAD

**Issue by llvvrui** [SubmarinerApp/Submariner#149]
<img width="260" alt="Snipaste_2023-07-30_10-02-43" src="https://github.com/SubmarinerApp/Submariner/assets/38856163/0f2e395a-e2cf-4a95-acd2-6b7aa108aa73">

**Comment by NattyNarwhal** [comment]
What version is this? Do you have anything in Console.app about i.e. keychain issues?

**Comment by llvvrui** [comment]
Thank you @NattyNarwhal ,I reset password,program is running.I use password "wabmiv-4Kevxo-ruswis" ago.
