### ISSUE TITLE
Parse disc number

### ISSUE THREAD

**Issue by jlxip** [SubmarinerApp/Submariner#153]
Submariner does not parse the disc number field of the files metadata, which makes multi-disc albums hard to listen. [See here](https://imgur.com/a/95oW2TM). While this is a common problem in Subsonic clients, implementing it should be easy enough.

**Comment by NattyNarwhal** [comment]
[It actually is](https://github.com/SubmarinerApp/Submariner/blob/master/Submariner/SBSubsonicParsingOperation.swift#L938-L940), though there's no column for it. The [default sort order](https://github.com/SubmarinerApp/Submariner/blob/master/Submariner/SBServerLibraryController.m#L98-L100) is disc then track, but there is no obvious way to reset it back to that if you change the ordering.

<img width="272" alt="Screenshot 2023-08-14 at 5 13 51 PM" src="https://github.com/SubmarinerApp/Submariner/assets/3161292/45707ca7-4ad0-424e-b778-2cc96b2b5768">

Try removing the saved sort order, run `defaults delete fr.read-write.Submariner "NSTableView Sort Ordering v2 ServerMusicTable"`. There should be a way to reset it back to disc then track from the UI though.

**Comment by jlxip** [comment]
Cool, that will help me as a temporal solution. Thanks!!

**Comment by NattyNarwhal** [comment]
Looks like I [already this this](https://github.com/SubmarinerApp/Submariner/commit/c114d0d5617d00d6166450a73e2983379387062f) - sorting by track should make it sort by disc too.
