### ISSUE TITLE
When connecting to a server for the first time, requires manually triggering "Reload Server"

### ISSUE THREAD

**Issue by GetOutOfMyBakery** [SubmarinerApp/Submariner#159]
# What
Another follow on from [this comment](https://github.com/SubmarinerApp/Submariner/issues/157#issuecomment-1686687340).
When you connect to a new server for the first time, it does not auto-populate with artists, album, and tracks, you have to select the server and manually trigger `Reload Server`.

# Steps to reproduce
1. With Submariner open, connect to a new valid server
2. Click on the newly connected server
3. No music is available (Screenshot below)
5. Right click and select `Reload Server`
6. All music now shows up

# Expected behaviour
On connecting to a new server, the discovery should be triggered automatically and pick up all current music.

## Screenshots
<img width="451" alt="image" src="https://github.com/SubmarinerApp/Submariner/assets/12701930/3019007e-6338-4321-b79b-8dd7fe37c97e">

## Versions
- Navidrome `0.49.3 (8b93962f)`
- Submariner 2.4 (installed via `brew`)

**Comment by NattyNarwhal** [comment]
I caught this regression in 9181e677ca2723d94231db821d960c00d4e3abd5, should be fixed in next release
