### ISSUE TITLE
Navidrome server can't be accesses

### ISSUE THREAD

**Issue by tehabe** [SubmarinerApp/Submariner#170]
**Describe the bug**
When I try to add a Navidrome server to SubMariner, the server's music is not displayed but also not a single error message.

**To Reproduce**
1. Go to 'New Server'
2. Fill out the needed information

![Screenshot 2023-10-15 at 18 55 17](https://github.com/SubmarinerApp/Submariner/assets/67130363/030fea53-6232-4b57-a03c-a6198059c724)

4. Click Okay

<img width="138" alt="Screenshot 2023-10-15 at 18 53 33" src="https://github.com/SubmarinerApp/Submariner/assets/67130363/7acd6488-b777-4f16-bdd2-ba2181b0f42e">

**Expected behavior**
Music should be displayed and playable

**Screenshots**
<img width="651" alt="Screenshot 2023-10-15 at 18 47 56" src="https://github.com/SubmarinerApp/Submariner/assets/67130363/f6f79951-a475-44c2-9d43-8c2d725cd412">

**Versions:**
 - macOS [e.g. 13.5]: 14.0
 - Subsonic Server and Version [e.g. Navidrome 0.44, Subsonic 6.1.6]: Navidrome 0.49.3
 - Submariner Version [e.g. 2.2]: Submariner 2.4.2
 - Download Source [e.g. Mac App Store]: Tried both.

**Comment by NattyNarwhal** [comment]
Do you see anything in Console.app? Be sure to check info/debug messages from the view menu if so.

Missing "u" makes me think it could be an issue with the username somehow not getting included when it builds the URL. That could be say, Keychain related, but without the URL it's harder to find out.

**Comment by tehabe** [comment]
I attempted again, also to get you the log files, and suddently it worked. I have no idea what I did differently now. Very weird.

**Comment by tehabe** [comment]
I attempted again, also to get you the log files, and suddently it worked. I have no idea what I did differently now. Very weird.

**Comment by Scaffale** [comment]
I still got this error.

Navidrome [0.50.1](https://github.com/navidrome/navidrome/releases/tag/v0.50.1)
Sumariner 2.4.2
both direct download and brew

> Do you see anything in Console.app? Be sure to check info/debug messages from the view menu if so.
I don't understand where is the console.app I'm supposed to check...

tried also with [Gonic](https://github.com/sentriz/gonic) and same thing.

**Comment by NattyNarwhal** [comment]
Console.app is in the Utilities folder under Applications. Or open it from Spotlight.

**Comment by 4volodin** [comment]
I had the same issue when used autofill. 
I solved that simply - copy password and paste it manually
