### ISSUE TITLE
Ogg Vorbis files do not play

### ISSUE THREAD

**Issue by amigan** [SubmarinerApp/Submariner#186]
**Describe the bug**
Ogg Vorbis files will not play. The seek bar stays at 0:00, no error is thrown, and nothing happens. MP3, M4A, and FLACs play fine, however.

**To Reproduce**
1. Play an Ogg Vorbis file.

**Expected behavior**
Hear the music, be able to seek around the file.

**Versions:**
 - macOS 12.7.2
 - Navidrome 0.49.3
 - Submariner v3.0
 - From github releases

**Additional context**
I have seen playing an ogg file after a file of a different format cause the seek handle to remain in its previous position, but the time still says 0:00.

**Comment by NattyNarwhal** [comment]
The system APIs (AVFoundation/AudioToolbox) don't support Vorbis. See [here](https://github.com/SubmarinerApp/Submariner/wiki/Supported-Audio-Formats) for the list of supported formats from my testing.

If the server does transcoding, you can probably make it transcode Vorbis to something else for streams.

**Comment by amigan** [comment]
Aye, that is quite unfortunate, especially considering the xiph Vorbis component hasn't been a thing for quite some time. No fault of this project, of course, only of Mother Apple who knows what is best for us. Closing.

**Comment by Khazbs** [comment]
Thanks, Apple!
