### ISSUE TITLE
Disc support in the track list

### ISSUE THREAD

**Issue by skyline75489** [SubmarinerApp/Submariner#188]
**Describe the bug**

Tracks from different discs are incorrectly organized in the track list.

**To Reproduce**

<img width="1280" alt="截屏2024-01-22 15 26 47" src="https://github.com/SubmarinerApp/Submariner/assets/4710575/cff7bacb-9c8a-4da4-a3b2-fa644f3eaa48">

Note how the track with No.1 is grouped together. They're from different discs

**Expected behavior**

<img width="1280" alt="截屏2024-01-22 15 27 11" src="https://github.com/SubmarinerApp/Submariner/assets/4710575/cdb2594e-688c-4942-ab25-90dcfc25bc16">

**Screenshots**

**Versions:**
 - macOS: 14.0
 - Subsonic Server and Version: Navidrome 0.52
 - Submariner Version: 3.0
 - Download Source: GitHub Release

**Additional context**

**Comment by NattyNarwhal** [comment]
Odd, the default sort order should be disc-then-track; there's a method assigned to the table's delegate that should also force that sort order if you click the disc number column. If that doesn't work, I'd wondered why. I'm also using Navidrome, so it should understand disc numbers coming back from responses. too.

FWIW, there is the "use more violence approach" - the table sort descriptors seem to be saved in default keys prefixed with `NSTableView Sort Ordering v2`.

**Comment by skyline75489** [comment]
Yeah...clicking the dis number column fixes the order, and the wrong order is gone forever.

**Comment by NattyNarwhal** [comment]
Good to know that fixes it, though it's a little strange that it got that way in the first place. Do you remember anything that happened that might have changed the sort order?

**Comment by skyline75489** [comment]
Nothing really. I just launch the app the first thing I see is the wrong order in the screenshot.

**Comment by blindmanonacid** [comment]
Hi, just want to mention that on a fresh install the tracks are still not organized by disc number. After searching the issue I came upon this report and clicking the number column have solved it.
