### ISSUE TITLE
Can't skip or autoplay next track

### ISSUE THREAD

**Issue by double-u-a** [SubmarinerApp/Submariner#200]
**Describe the bug**
Can't skip or autoplay next track

**To Reproduce**
1. When track ends music stops playing and can't skip to next track

**Expected behavior**
Music to continue playing playlist, skip button to skip to next song in playlist

**Versions:**
 - macOS: 14.4
 - Subsonic Server and Version: Navidrome [0.51.0](https://github.com/navidrome/navidrome/releases/tag/v0.51.0) (fd61b29a)
 - Submariner Version: 3.0
 - Download Source: Mac App store

**Comment by NattyNarwhal** [comment]
Sorry for the late response.

Does it move onto the next track, or does it try to play the next track and fail? Is there anything in the [console](https://github.com/SubmarinerApp/Submariner/wiki/Getting-diagnostics-in-Console.app)?

**Comment by double-u-a** [comment]
These were the two warnings/errors I can see in console.app for Submariner when I try and skip track

```
Two equal instances have unequal identities. <type=Application identifier=application.fr.read-write.Submariner.63018006.63018012 AUID=501> and <type=Application identifier=application.fr.read-write.Submariner.63018006.63018012>`

`nw_resolver_start_query_timer_block_invoke [C17.1] Query fired: did not receive all answers in time for Hostname#REDACTED:4533
```

**Comment by double-u-a** [comment]
Reinstalled same version and readded server and issue has gone, will re-open if it resurfaces again
