### ISSUE TITLE
artist starting with lowercase ends up in [Unknown]

### ISSUE THREAD

**Issue by dxlr8r** [SubmarinerApp/Submariner#206]
As subject says. When renaming first letter to uppercase, sorting is fixed. IMO sorting should not care about case, so both A and a should be under "A".

**Comment by NattyNarwhal** [comment]
I'm not entirely pleased by the solution; it handles the `[Unknown]` entries poorly. I'm tempted to special case it, or preserve the ordering provided by the server.

**Comment by NattyNarwhal** [comment]
It should handle those entries better now. Server order raises some other implications (mostly around the fact we'd need to reorder it anyways or change the schema), so I'm hesitant but interested still.

**Comment by dxlr8r** [comment]
I have version 3.1.1, and I can confirm that an artist starting with a lower-case "a" appears under `[Unknown]`

**Comment by NattyNarwhal** [comment]
Next version will sort in a case insensitive way. I also special-cased the [Unknown] entries since they sorted oddly.
